site_name: joaoprocopio
site_url: https://joaoprocopio.github.io/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: deep-purple
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      primary: deep-purple
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
